import type { Product } from "./nutriscore";

// Simulated Naivas.co.ke product catalog. In the real extension these are
// scraped from the host DOM and matched against a local nutrient database.
export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Brookside Fresh Milk 500ml",
    brand: "Brookside",
    category: "Beverages — Dairy",
    price: "KSh 65",
    imageUrl:
      "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&q=80",
    grade: "B",
    negativePoints: 4,
    confidence: "measured",
    perUnit: "ml",
    nutrients: {
      energyKj: 268,
      fatG: 3.4,
      satFatG: 2.1,
      carbsG: 4.8,
      sugarsG: 4.8,
      fibreG: 0,
      proteinG: 3.3,
      sodiumMg: 44,
    },
  },
  {
    id: "p2",
    name: "Coca-Cola Soda 500ml",
    brand: "Coca-Cola",
    category: "Beverages — Soft Drinks",
    price: "KSh 70",
    imageUrl:
      "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80",
    grade: "E",
    negativePoints: 22,
    confidence: "measured",
    perUnit: "ml",
    nutrients: {
      energyKj: 190,
      fatG: 0,
      satFatG: 0,
      carbsG: 10.6,
      sugarsG: 10.6,
      fibreG: null,
      proteinG: 0,
      sodiumMg: 8,
    },
  },
  {
    id: "p3",
    name: "Daima Fresh Spinach 250g",
    brand: "Daima",
    category: "Vegetables — Fresh",
    price: "KSh 40",
    imageUrl:
      "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80",
    grade: "A",
    negativePoints: 0,
    confidence: "measured",
    perUnit: "g",
    nutrients: {
      energyKj: 97,
      fatG: 0.4,
      satFatG: 0.05,
      carbsG: 3.6,
      sugarsG: 0.4,
      fibreG: 2.2,
      proteinG: 2.9,
      sodiumMg: 79,
    },
  },
  {
    id: "p4",
    name: "Tropical Heat Crisps 100g",
    brand: "Tropical Heat",
    category: "Snacks — Salty",
    price: "KSh 120",
    imageUrl:
      "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&q=80",
    grade: "D",
    negativePoints: 15,
    confidence: "derived",
    perUnit: "g",
    nutrients: {
      energyKj: 2210,
      fatG: 34,
      satFatG: 12,
      carbsG: 50,
      sugarsG: 1.2,
      fibreG: 4.1,
      proteinG: 6,
      sodiumMg: 540,
    },
  },
  {
    id: "p5",
    name: "Weetabix Whole Grain 500g",
    brand: "Weetabix",
    category: "Cereals — Breakfast",
    price: "KSh 480",
    imageUrl:
      "https://images.unsplash.com/photo-1614961233913-a5113a4a34ed?w=400&q=80",
    grade: "A",
    negativePoints: 2,
    confidence: "measured",
    perUnit: "g",
    nutrients: {
      energyKj: 1500,
      fatG: 2,
      satFatG: 0.6,
      carbsG: 69,
      sugarsG: 4.4,
      fibreG: 10,
      proteinG: 12,
      sodiumMg: 110,
    },
  },
  {
    id: "p6",
    name: "Blue Band Margarine 250g",
    brand: "Blue Band",
    category: "Fats & Spreads",
    price: "KSh 195",
    imageUrl:
      "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400&q=80",
    grade: "D",
    negativePoints: 14,
    confidence: "fallback",
    perUnit: "g",
    nutrients: {
      energyKj: 2400,
      fatG: 60,
      satFatG: 18,
      carbsG: 0.5,
      sugarsG: 0.5,
      fibreG: null,
      proteinG: 0.2,
      sodiumMg: 640,
    },
  },
  {
    id: "p7",
    name: "Kenchic Chicken Sausages 400g",
    brand: "Kenchic",
    category: "Meat — Processed",
    price: "KSh 350",
    imageUrl:
      "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&q=80",
    grade: "C",
    negativePoints: 9,
    confidence: "derived",
    perUnit: "g",
    nutrients: {
      energyKj: 920,
      fatG: 16,
      satFatG: 5.5,
      carbsG: 4,
      sugarsG: 1,
      fibreG: 0.5,
      proteinG: 13,
      sodiumMg: 780,
    },
  },
  {
    id: "p8",
    name: "Del Monte Orange Juice 1L",
    brand: "Del Monte",
    category: "Beverages — Juices",
    price: "KSh 250",
    imageUrl:
      "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&q=80",
    grade: "C",
    negativePoints: 8,
    confidence: "measured",
    perUnit: "ml",
    nutrients: {
      energyKj: 188,
      fatG: 0.1,
      satFatG: 0.02,
      carbsG: 10.5,
      sugarsG: 9.8,
      fibreG: 0.2,
      proteinG: 0.7,
      sodiumMg: 5,
    },
  },
];
