/**
 * scripts/build-db.mjs
 * Compiles src/ui/src/app/lib/db.ts -> src/extension/db.js
 *
 * Ensures background.js and the React dashboard share ONE source of truth
 * for the data layer. Run via: npm run build:db
 */

import { build } from "esbuild";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

await build({
  entryPoints: [resolve(root, "src/ui/src/app/lib/db.ts")],
  bundle: true,
  outfile: resolve(root, "src/extension/db.js"),
  format: "iife",
  globalName: "NutriScoreDB",
  platform: "browser",
  target: ["chrome96"],
  minify: false,
  sourcemap: false,
  external: [],
  banner: {
    js: "// AUTO-GENERATED by scripts/build-db.mjs -- do not hand-edit.\n// Source: src/ui/src/app/lib/db.ts\n",
  },
  logLevel: "info",
});

console.log("[build-db] src/extension/db.js updated from db.ts");
