import fs from 'fs';
import path from 'path';

function copyDir(src, dest) {
  if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

// Ensure public directory exists
const publicDir = path.resolve('public');
if (fs.existsSync(publicDir)) {
  try {
    fs.rmSync(publicDir, { recursive: true, force: true });
  } catch (err) {
    console.warn('Could not remove public directory (it may be locked by another process like a local server). Files will be overwritten.');
  }
}
if (!fs.existsSync(publicDir)) {
  fs.mkdirSync(publicDir, { recursive: true });
}

// 1. Copy webpage static files (html, css, assets)
console.log('Copying webpage static files to public...');
const webpageDir = path.resolve('webpage');
const webpageFiles = fs.readdirSync(webpageDir);
for (const file of webpageFiles) {
  if (['dist', 'node_modules', 'package.json', 'package-lock.json', 'build.js'].includes(file)) continue;
  const srcPath = path.join(webpageDir, file);
  const destPath = path.join(publicDir, file);
  if (fs.statSync(srcPath).isDirectory()) {
    copyDir(srcPath, destPath);
  } else {
    fs.copyFileSync(srcPath, destPath);
  }
}

// 2. Copy webpage build artifacts (dist folder contents)
console.log('Copying webpage build artifacts to public...');
const webpageDistDir = path.join(webpageDir, 'dist');
if (fs.existsSync(webpageDistDir)) {
  copyDir(webpageDistDir, publicDir);
}

// 3. Copy UI dashboard build artifacts (dist folder contents -> public/dashboard)
console.log('Copying UI dashboard artifacts to public/dashboard...');
const uiDistDir = path.resolve('dist'); // the root dist generated by vite
const publicDashboardDir = path.join(publicDir, 'dashboard');
if (fs.existsSync(uiDistDir)) {
  copyDir(uiDistDir, publicDashboardDir);
}

console.log('Deployment preparation complete. Output in public/');
